version: '3.8'

services:
  backend:
    container_name: nestjs-backend
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./back:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production

  frontend:
    container_name: vue-frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./front:/app
      - /app/node_modules

networks:
  default:
    driver: bridge